data: /home/mitic-20/Desktop/3D_reconstruction/simcol-main/data_for_TRAIN
folder_type: sequence
sequence_length: 3
workers: 4
epochs: 50
epoch_size: 8067
batch_size: 8
lr: 0.0001
momentum: 0.9
beta: 0.999
weight_decay: 0
print_freq: 10
frames_apart: 1
seed: 0
log_summary: progress_log_summary.csv
log_full: progress_log_full.csv
log_output: false
resnet_layers: 18
num_scales: 1
photo_loss_weight: 1
smooth_loss_weight: 0.1
geometry_consistency_weight: 0.5
endo_slam_weight: 1
class_w: 0.1
with_ssim: 1
with_mask: 1
cross_num: '1'
with_auto_mask: 0
with_pretrain: 1
with_resize: 1
dataset: S
val_dataset: S
pretrained_disp: null
pretrained_pose: null
name: posenet_retrained
padding_mode: zeros
with_gt: false
train_file: data/train_file.txt
val_file: data/val_file.txt
pose_model: posecorrnet
pose_decoder: conv
fs: 256
im_size: 256
embedded_size: 16
binned: 1
save_path: !!python/object/new:path.Path
- trained_models/posenet_retrained/08-18-16:14
